---
title: CrimeProject2
subtitle: CPSC 292 Section -- 2 (Hanson)
author: Natalia Cuyler and Mariela Rodriguez
date: 11/16/2022
output: html_notebook
---


###New Bar Graph1 Using Functions/If Else - Murder Arrests

```{r, include=T}
library(ggplot2)
library(patchwork)

#read.csv("~/Desktop/CPSC292/data/US_violent_crime.csv")
us.violent.crime <- read.csv("~/Desktop/CPSC292/CrimeProject1/US_violent_crime 2.csv")


```

```{r, include=T}
state <- us.violent.crime[,1]
murder <- us.violent.crime[,2]
assault <- us.violent.crime[,3]
urbanpop <- us.violent.crime[,4]
rape <- us.violent.crime[,5]
```

```{r, include=T}
murder > 9
ifelse(murder >= 9, state, NA)
our.states <- ifelse(murder >= 9, state, NA)

our.murders <- ifelse(murder >= 9, murder, NA)

our.states1 <- na.omit(our.states)
our.states1

murders <- na.omit(our.murders)
murders

murders.by.state <- data.frame(our.states1, murders)

ggplot(murders.by.state, aes(x=our.states1, y=murders, fill=murders)) +
  geom_bar(stat="identity") +
  xlab("State") +
  ylab("Murder Arrests > 9") +
  ggtitle("US States With More Than 9/1,000 Violent Arrests") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 90, size = 5)) 

  
```

```{r, include=T}
new.plot1 <- function(murder) {
  ggplot(us.violent.crime, aes_string(x="X",y=murder, fill=murder)) +
       xlab("State") +
       ylab("Arrests per 1,000") +
       ggtitle(paste(murder, "Arrests per 1,000 by US State")) + 
  geom_bar(stat="identity") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.text.x = element_text(angle = 90, size = 5)) 
}


new.plot1("Murder") / new.plot1("Assault")

 
```